# components/place_types.py

PLACE_TYPES = {
    "教育": [
        "圖書館", "library",
        "幼兒園", "kindergarten",
        "托兒所", "child care",
        "小學", "elementary school",
        "國中", "junior high school",
        "高中", "high school",
        "大學", "university",
        "補習班", "cram school",
        "學校", "school",
    ],
    "購物": [
        "超市", "supermarket",
        "便利商店", "convenience store",
        "全聯福利中心", "Pxmart",
        "家樂福", "Carrefour",
        "大潤發", "RT-MART",
        "好市多", "Costco",
        "屈臣氏", "Watsons",
        "康是美", "COSMED",
        "寶雅", "Poya",
        "藥妝店", "drugstore",
        "五金行", "hardware store",
        "家具行", "furniture store",
        "書局", "bookstore",
        "文具店", "stationery store",
        "手機行", "mobile phone store",
        "電腦賣場", "computer store",
        "服飾店", "clothing store",
        "鞋店", "shoe store",
        "眼鏡行", "eyeglasses store",
        "百貨公司", "department store",
        "購物中心", "shopping mall",
        "市場", "market",
        "傳統市場", "traditional market",
        "夜市", "night market",
        "批發", "wholesale market",
    ],
    "交通運輸": [
        "公車站", "bus station",
        "捷運站", "MRT station",
        "火車站", "train station",
        "高鐵站", "HSR station",
        "客運站", "bus terminal",
        "計程車行", "taxi service",
        "停車場", "parking lot",
        "加油站", "gas station",
        "YouBike", "YouBike",
        "機車行", "motorcycle repair",
        "汽車維修", "car repair",
    ],
    "健康與保健": [
        "醫院", "hospital",
        "診所", "clinic",
        "衛生所", "public health center",
        "藥局", "pharmacy",
        "牙醫診所", "dentist",
        "中醫診所", "Chinese medicine clinic",
        "西醫診所", "medical clinic",
        "小兒科診所", "pediatric clinic",
        "婦產科診所", "obstetrics and gynecology clinic",
        "眼科診所", "ophthalmology clinic",
        "皮膚科診所", "dermatology clinic",
        "復健科診所", "rehabilitation clinic",
        "物理治療所", "physical therapy",
        "按摩店", "massage",
        "養生館", "wellness center",
        "SPA", "spa",
        "健身中心", "fitness center",
        "健身房", "gym",
        "瑜珈教室", "yoga studio",
        "運動中心", "sports center",
    ],
    "餐飲美食": [
        "餐廳", "restaurant",
        "小吃店", "snack shop",
        "早餐店", "breakfast shop",
        "咖啡廳", "cafe",
        "星巴克", "Starbucks",
        "路易莎咖啡", "Louisa Coffee",
        "85度C", "85度C",
        "手搖飲料店", "bubble tea",
        "飲料店", "drink shop",
        "速食店", "fast food",
        "麥當勞", "McDonald's",
        "肯德基", "KFC",
        "摩斯漢堡", "Mos Burger",
        "漢堡王", "Burger King",
        "披薩店", "pizza restaurant",
        "達美樂披薩", "Domino's Pizza",
        "拿坡里披薩", "Napoli Pizza",
        "必勝客", "Pizza Hut",
        "火鍋店", "hot pot restaurant",
        "燒烤店", "barbecue restaurant",
        "牛排館", "steak house",
        "鐵板燒", "teppanyaki",
        "日本料理", "Japanese restaurant",
        "壽司店", "sushi restaurant",
        "拉麵店", "ramen restaurant",
        "韓式料理", "Korean restaurant",
        "泰式料理", "Thai restaurant",
        "越南料理", "Vietnamese restaurant",
        "美式餐廳", "American restaurant",
        "義大利麵餐廳", "Italian restaurant",
        "自助餐", "buffet",
        "便當店", "lunch box",
        "麵店", "noodle shop",
        "滷味店", "braised food",
        "鹽酥雞", "fried chicken",
        "雞排店", "chicken cutlet",
        "甜點店", "dessert shop",
        "蛋糕店", "cake shop",
        "麵包店", "bakery",
        "冰店", "ice shop",
        "豆花店", "tofu pudding",
    ],
    "生活服務": [
        "銀行", "bank",
        "郵局", "post office",
        "派出所", "police station",
        "警察局", "police department",
        "消防局", "fire station",
        "區公所", "district office",
        "戶政事務所", "household registration office",
        "運動公園", "sports park",
        "公園", "park",
        "兒童公園", "children's park",
        "河濱公園", "riverside park",
        "廟宇", "temple",
        "教堂", "church",
        "洗車場", "car wash",
        "汽車美容", "car detailing",
        "洗衣店", "laundry",
        "影印店", "printing shop",
        "電信行", "telecom store",
        "中華電信", "Chunghwa Telecom",
        "台灣大哥大", "Taiwan Mobile",
        "遠傳電信", "Far EasTone",
        "寵物店", "pet store",
        "動物醫院", "animal hospital",
    ]
}

# 建立反向映射
ENGLISH_TO_CHINESE = {}
for category, items in PLACE_TYPES.items():
    for i in range(0, len(items), 2):
        if i+1 < len(items):
            ENGLISH_TO_CHINESE[items[i+1]] = items[i]
